# theme: jekyll-theme-dinky

title: Conceptos de Python y R
author:
  name: GitHub User
  email: sergio.sanes@udea.edu.co
show_downloads: true
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Estas notas esta dirigidas a los estudiantes del curso Conceptos de Python y R.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
# theme: jekyll-theme-architect
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
